
  datasource:
    url: jdbc:mysql://localhost:3306/your_database?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver
